name: Build, test and deliver container

on: push

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Java 11 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Start MariaDB for integration test
        uses: getong/mariadb-action@v1.1
        with:
          mysql database: 'studio' # Optional, default value is "test". The specified database which will be created.
          mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password

      - name: Build, test and package project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Victonator_geavanceerde-programmeer-onderwerpen-studios-backend

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/geavanceerde-programmeer-onderwerpen-studios-backend:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/geavanceerde-programmeer-onderwerpen-studios-backend:latest
